#!/bin/sh

str="SCRIPT -"
echo "$str Making test directory\n"
mkdir dn
cd dn

echo "$str Cloning Darknet and make\n"
git clone https://github.com/pjreddie/darknet.git
cd darknet
make

echo "$str Downloading YOLO training set\n"

dir="vocTrainingDir"
mkdir $dir
cd $dir
#<<comments
wget https://pjreddie.com/media/files/VOCtrainval_11-May-2012.tar
wget https://pjreddie.com/media/files/VOCtrainval_06-Nov-2007.tar
wget https://pjreddie.com/media/files/VOCtest_06-Nov-2007.tar
tar xf VOCtrainval_11-May-2012.tar
tar xf VOCtrainval_06-Nov-2007.tar
tar xf VOCtest_06-Nov-2007.tar

wget https://pjreddie.com/media/files/voc_label.py
python voc_label.py

cat 2007_train.txt 2007_val.txt 2012_*.txt > train.txt
#comments

echo "$str Modifying  Config File"
cfgPath="../cfg/voc.data"
cwd=$(pwd)
rm $cfgPath
echo "classes= 20" > $cfgPath
echo "train = $cwd/train.txt" >> $cfgPath
echo "valid = $cwd/2007_test.txt" >> $cfgPath
echo "names = data/voc.names" >> $cfgPath
echo "backup = backup" >> $cfgPath
cd ..

echo "$str Downloading training weights?"
wget https://pjreddie.com/media/files/darknet53.conv.74

echo "$str Should be ready for training"
